2021-01-05 20:45:18,816--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:45:23,101--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:15163216682]
2021-01-05 20:45:24,972--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15163216682', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:45:25,106--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:45:25,889--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15163216682]
2021-01-05 20:45:26,005--->>[fixture.py--->line:59--INFO-->>用户:10023890登录成功]
2021-01-05 20:45:39,089--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:15860753575]
2021-01-05 20:45:39,644--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15860753575', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:45:39,780--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:45:40,506--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15860753575]
2021-01-05 20:45:40,627--->>[fixture.py--->line:59--INFO-->>用户:10023894登录成功]
2021-01-05 20:45:45,768--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26281]
2021-01-05 20:45:45,769--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:45:45,913--->>[test_audit_project.py--->line:95--ERROR-->>审核成功数据库校验失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 87, in test_audit_project
    self.assertTrue(self.db.Isexist(sql=sql));
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/common/mysql_handler.py", line 27, in Isexist
    self.cur.execute(sql);
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1")
2021-01-05 20:45:45,922--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:46,029--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26282]
2021-01-05 20:45:46,030--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败<<---接口]
2021-01-05 20:45:46,176--->>[test_audit_project.py--->line:95--ERROR-->>审核失败数据库校验失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 92, in test_audit_project
    self.assertTrue(self.db.Isexist(sql=sql));
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/common/mysql_handler.py", line 27, in Isexist
    self.cur.execute(sql);
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1")
2021-01-05 20:45:46,178--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:46,302--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26283]
2021-01-05 20:45:46,302--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id为空<<---接口]
2021-01-05 20:45:46,387--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:46,489--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26284]
2021-01-05 20:45:46,490--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id不存在<<---接口]
2021-01-05 20:45:46,579--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:46,680--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26285]
2021-01-05 20:45:46,680--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目ID为字符串<<---接口]
2021-01-05 20:45:46,772--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:46,867--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26286]
2021-01-05 20:45:46,868--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--多次审核<<---接口]
2021-01-05 20:45:46,963--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: 0 != 2
2021-01-05 20:45:46,965--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26286, 'approved_or_not': False}]
2021-01-05 20:45:46,965--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:45:46,965--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:45:46,965--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:47,079--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26287]
2021-01-05 20:45:47,080--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不存在<<---接口]
2021-01-05 20:45:47,170--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:45:47,270--->>[fixture.py--->line:119--INFO-->>该用户10023890加标借款成功:金额是:2000,该标的id是:26288]
2021-01-05 20:45:47,271--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不是true和false<<---接口]
2021-01-05 20:45:47,364--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:46:08,755--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:46:11,010--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:18308678257]
2021-01-05 20:46:11,187--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18308678257', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:46:11,308--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:46:11,604--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18308678257]
2021-01-05 20:46:11,717--->>[fixture.py--->line:59--INFO-->>用户:10023895登录成功]
2021-01-05 20:46:12,395--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:15516241466]
2021-01-05 20:46:12,604--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15516241466', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:46:12,715--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:46:13,912--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15516241466]
2021-01-05 20:46:14,020--->>[fixture.py--->line:59--INFO-->>用户:10023896登录成功]
2021-01-05 20:46:17,420--->>[fixture.py--->line:119--INFO-->>该用户10023895加标借款成功:金额是:2000,该标的id是:26295]
2021-01-05 20:46:52,599--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:48:40,988--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:48:41,045--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:15436307305]
2021-01-05 20:48:41,045--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15436307305', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:48:41,160--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:48:41,160--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:48:41,161--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:48:41,161--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:49:01,456--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:49:01,523--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:13887202895]
2021-01-05 20:49:01,523--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13887202895', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:49:01,646--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:49:01,646--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13887202895]
2021-01-05 20:49:01,755--->>[fixture.py--->line:59--INFO-->>用户:10023900登录成功]
2021-01-05 20:49:01,820--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:15133030833]
2021-01-05 20:49:01,821--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15133030833', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:49:01,933--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:49:01,933--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15133030833]
2021-01-05 20:49:02,047--->>[fixture.py--->line:59--INFO-->>用户:10023901登录成功]
2021-01-05 20:49:06,191--->>[fixture.py--->line:119--INFO-->>该用户10023900加标借款成功:金额是:2000,该标的id是:26306]
2021-01-05 20:49:06,469--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:49:06,619--->>[test_audit_project.py--->line:95--ERROR-->>审核成功数据库校验失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 87, in test_audit_project
    self.assertTrue(self.db.Isexist(sql=sql));
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2021-01-05 20:49:06,619--->>[test_audit_project.py--->line:95--ERROR-->>审核成功数据库校验失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 87, in test_audit_project
    self.assertTrue(self.db.Isexist(sql=sql));
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
2021-01-05 20:49:21,390--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:49:21,457--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:18488219868]
2021-01-05 20:49:21,458--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18488219868', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:49:21,585--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:49:21,585--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18488219868]
2021-01-05 20:49:21,682--->>[fixture.py--->line:59--INFO-->>用户:10023905登录成功]
2021-01-05 20:49:21,734--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:13559662242]
2021-01-05 20:49:21,734--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13559662242', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:49:21,838--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:49:21,838--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13559662242]
2021-01-05 20:49:21,945--->>[fixture.py--->line:59--INFO-->>用户:10023906登录成功]
2021-01-05 20:49:38,259--->>[fixture.py--->line:119--INFO-->>该用户10023905加标借款成功:金额是:2000,该标的id是:26311]
2021-01-05 20:49:46,352--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:52:31,155--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:52:31,214--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:15455709818]
2021-01-05 20:52:31,215--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15455709818', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:52:31,315--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:52:31,315--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:52:31,315--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:52:31,315--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:52:43,954--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:52:44,013--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:15642073939]
2021-01-05 20:52:44,014--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15642073939', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:52:44,131--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:52:44,131--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15642073939]
2021-01-05 20:52:44,246--->>[fixture.py--->line:59--INFO-->>用户:10023914登录成功]
2021-01-05 20:52:44,303--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:15827452389]
2021-01-05 20:52:44,303--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15827452389', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:52:44,403--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:52:44,403--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15827452389]
2021-01-05 20:52:44,512--->>[fixture.py--->line:59--INFO-->>用户:10023915登录成功]
2021-01-05 20:52:49,278--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26322]
2021-01-05 20:52:49,544--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:52:49,708--->>[test_audit_project.py--->line:88--INFO-->>项目26322审核通过]
2021-01-05 20:52:58,274--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:53:00,005--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26324]
2021-01-05 20:53:01,691--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败<<---接口]
2021-01-05 20:53:47,517--->>[test_audit_project.py--->line:93--INFO-->>项目26324审核失败]
2021-01-05 20:53:49,557--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:53:50,724--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26332]
2021-01-05 20:53:53,146--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id为空<<---接口]
2021-01-05 20:54:03,740--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:54:05,047--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26333]
2021-01-05 20:54:09,421--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id不存在<<---接口]
2021-01-05 20:54:23,333--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:54:24,669--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26334]
2021-01-05 20:54:27,359--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目ID为字符串<<---接口]
2021-01-05 20:54:38,943--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:54:40,148--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26335]
2021-01-05 20:54:41,688--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--多次审核<<---接口]
2021-01-05 20:55:05,036--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: 0 != 2
2021-01-05 20:55:05,036--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: 0 != 2
2021-01-05 20:55:12,471--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26335, 'approved_or_not': False}]
2021-01-05 20:55:12,471--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26335, 'approved_or_not': False}]
2021-01-05 20:55:40,996--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:55:40,996--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:55:41,626--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:55:41,626--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:55:44,128--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:55:45,195--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26336]
2021-01-05 20:55:46,537--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不存在<<---接口]
2021-01-05 20:56:02,580--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:56:04,102--->>[fixture.py--->line:119--INFO-->>该用户10023914加标借款成功:金额是:2000,该标的id是:26337]
2021-01-05 20:56:22,069--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不是true和false<<---接口]
2021-01-05 20:56:34,146--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:00,533--->>[base_test_case.py--->line:36--INFO-->>开始测试加标接口]
2021-01-05 20:57:00,587--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13200605068', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:57:00,692--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:57:00,692--->>[test_add_project.py--->line:34--INFO-->>加标接口生成的手机号是:13200605068]
2021-01-05 20:57:00,693--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13200605068]
2021-01-05 20:57:00,797--->>[fixture.py--->line:59--INFO-->>用户:10023916登录成功]
2021-01-05 20:57:00,797--->>[test_add_project.py--->line:39--INFO-->>该用户是:10023916,登录成功]
2021-01-05 20:57:00,797--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标成功<<--接口]
2021-01-05 20:57:00,881--->>[test_add_project.py--->line:72--INFO-->>查询用户:10023916加标的sql是:select id from loan where member_id=10023916 and amount=2000 and title='yuejie专贷' and loan_date_type=1]
2021-01-05 20:57:00,928--->>[test_add_project.py--->line:74--INFO-->>该用户:10023916加标成功]
2021-01-05 20:57:00,929--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:00,929--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id为空<<--接口]
2021-01-05 20:57:01,019--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,020--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不是当前登录<<--接口]
2021-01-05 20:57:01,119--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,119--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不存在<<--接口]
2021-01-05 20:57:01,210--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,210--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--标题为空<<--接口]
2021-01-05 20:57:01,301--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,301--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为空<<--接口]
2021-01-05 20:57:01,392--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,392--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--年利率为空<<--接口]
2021-01-05 20:57:01,484--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,485--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限为空<<--接口]
2021-01-05 20:57:01,583--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,583--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型为空<<--接口]
2021-01-05 20:57:01,678--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,678--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数为空<<--接口]
2021-01-05 20:57:01,770--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,770--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型不是1和2<<--接口]
2021-01-05 20:57:01,857--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,858--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数大于10天<<--接口]
2021-01-05 20:57:01,953--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:01,954--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为负数<<--接口]
2021-01-05 20:57:02,041--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:02,042--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为小数<<--接口]
2021-01-05 20:57:02,135--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:57:02,135--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:57:02,195--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:18776789633]
2021-01-05 20:57:02,196--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18776789633', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:57:02,292--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:57:02,292--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18776789633]
2021-01-05 20:57:02,384--->>[fixture.py--->line:59--INFO-->>用户:10023917登录成功]
2021-01-05 20:57:02,437--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:13593110589]
2021-01-05 20:57:02,437--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13593110589', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:57:02,545--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:57:02,546--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13593110589]
2021-01-05 20:57:02,651--->>[fixture.py--->line:59--INFO-->>用户:10023918登录成功]
2021-01-05 20:57:02,743--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26339]
2021-01-05 20:57:02,743--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:57:02,872--->>[test_audit_project.py--->line:88--INFO-->>项目26339审核通过]
2021-01-05 20:57:02,873--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:02,958--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26340]
2021-01-05 20:57:02,959--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败<<---接口]
2021-01-05 20:57:03,104--->>[test_audit_project.py--->line:93--INFO-->>项目26340审核失败]
2021-01-05 20:57:03,104--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:03,197--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26341]
2021-01-05 20:57:03,197--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id为空<<---接口]
2021-01-05 20:57:03,292--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:03,397--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26342]
2021-01-05 20:57:03,397--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id不存在<<---接口]
2021-01-05 20:57:03,486--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:03,575--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26343]
2021-01-05 20:57:03,575--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目ID为字符串<<---接口]
2021-01-05 20:57:03,668--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:03,750--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26344]
2021-01-05 20:57:03,751--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--多次审核<<---接口]
2021-01-05 20:57:03,839--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:57:03,839--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:57:03,840--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26344, 'approved_or_not': False}]
2021-01-05 20:57:03,840--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26344, 'approved_or_not': False}]
2021-01-05 20:57:03,841--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:57:03,841--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:57:03,841--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:57:03,841--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:57:03,841--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:03,937--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26345]
2021-01-05 20:57:03,937--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不存在<<---接口]
2021-01-05 20:57:04,032--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:04,128--->>[fixture.py--->line:119--INFO-->>该用户10023917加标借款成功:金额是:2000,该标的id是:26346]
2021-01-05 20:57:04,129--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不是true和false<<---接口]
2021-01-05 20:57:04,221--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:57:04,221--->>[base_test_case.py--->line:36--INFO-->>开始测试登录接口]
2021-01-05 20:57:04,320--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:57:04,421--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:57:04,507--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:57:04,602--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:57:04,691--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:57:04,691--->>[base_test_case.py--->line:36--INFO-->>开始测试充值接口]
2021-01-05 20:57:04,744--->>[test_recharge.py--->line:34--INFO-->>测试充值接口生成的手机号是:18427029214]
2021-01-05 20:57:04,744--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18427029214', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:57:04,850--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:57:04,850--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18427029214]
2021-01-05 20:57:04,953--->>[fixture.py--->line:59--INFO-->>用户:10023919登录成功]
2021-01-05 20:57:04,953--->>[test_recharge.py--->line:40--INFO-->>当前用户10023919登录成功]
2021-01-05 20:57:04,954--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--整数<<--接口=====]
2021-01-05 20:57:04,954--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023919充值之前的sql是:select leave_amount from member where id='10023919']
2021-01-05 20:57:04,998--->>[test_recharge.py--->line:56--INFO-->>该用户:10023919充值之前的余额是:0.00]
2021-01-05 20:57:04,998--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:05,137--->>[test_recharge.py--->line:78--INFO-->>该用户:10023919,充值之后的余额是:10000.00]
2021-01-05 20:57:05,137--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023919充值成功]
2021-01-05 20:57:05,137--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:57:05,137--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023919是否生成流水账单]
2021-01-05 20:57:05,137--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023919 生成流水账单的sql是:select id from financelog where income_member_id='10023919' and amount=10000 and income_member_money=10000.00]
2021-01-05 20:57:05,199--->>[test_recharge.py--->line:106--INFO-->>该用户:10023919生成流水账单校验通过]
2021-01-05 20:57:05,200--->>[test_recharge.py--->line:107--INFO-->>该用户10023919充值成功，充值的金额是:10000]
2021-01-05 20:57:05,200--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:05,200--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--一位小数<<--接口=====]
2021-01-05 20:57:05,200--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023919充值之前的sql是:select leave_amount from member where id='10023919']
2021-01-05 20:57:05,241--->>[test_recharge.py--->line:56--INFO-->>该用户:10023919充值之前的余额是:10000.00]
2021-01-05 20:57:05,241--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:05,367--->>[test_recharge.py--->line:78--INFO-->>该用户:10023919,充值之后的余额是:10100.20]
2021-01-05 20:57:05,367--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023919充值成功]
2021-01-05 20:57:05,367--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:57:05,368--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023919是否生成流水账单]
2021-01-05 20:57:05,368--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023919 生成流水账单的sql是:select id from financelog where income_member_id='10023919' and amount=100.2 and income_member_money=10100.20]
2021-01-05 20:57:05,429--->>[test_recharge.py--->line:106--INFO-->>该用户:10023919生成流水账单校验通过]
2021-01-05 20:57:05,429--->>[test_recharge.py--->line:107--INFO-->>该用户10023919充值成功，充值的金额是:100.2]
2021-01-05 20:57:05,429--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:05,429--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--2位小数<<--接口=====]
2021-01-05 20:57:05,429--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023919充值之前的sql是:select leave_amount from member where id='10023919']
2021-01-05 20:57:05,469--->>[test_recharge.py--->line:56--INFO-->>该用户:10023919充值之前的余额是:10100.20]
2021-01-05 20:57:05,470--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:05,616--->>[test_recharge.py--->line:78--INFO-->>该用户:10023919,充值之后的余额是:10200.43]
2021-01-05 20:57:05,616--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023919充值成功]
2021-01-05 20:57:05,616--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:57:05,616--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023919是否生成流水账单]
2021-01-05 20:57:05,616--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023919 生成流水账单的sql是:select id from financelog where income_member_id='10023919' and amount=100.23 and income_member_money=10200.43]
2021-01-05 20:57:05,669--->>[test_recharge.py--->line:106--INFO-->>该用户:10023919生成流水账单校验通过]
2021-01-05 20:57:05,670--->>[test_recharge.py--->line:107--INFO-->>该用户10023919充值成功，充值的金额是:100.23]
2021-01-05 20:57:05,670--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:05,671--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--50万<<--接口=====]
2021-01-05 20:57:05,671--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023919充值之前的sql是:select leave_amount from member where id='10023919']
2021-01-05 20:57:05,714--->>[test_recharge.py--->line:56--INFO-->>该用户:10023919充值之前的余额是:10200.43]
2021-01-05 20:57:05,714--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:05,860--->>[test_recharge.py--->line:78--INFO-->>该用户:10023919,充值之后的余额是:510200.43]
2021-01-05 20:57:05,860--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023919充值成功]
2021-01-05 20:57:05,860--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:57:05,860--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023919是否生成流水账单]
2021-01-05 20:57:05,861--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023919 生成流水账单的sql是:select id from financelog where income_member_id='10023919' and amount=500000 and income_member_money=510200.43]
2021-01-05 20:57:05,914--->>[test_recharge.py--->line:106--INFO-->>该用户:10023919生成流水账单校验通过]
2021-01-05 20:57:05,914--->>[test_recharge.py--->line:107--INFO-->>该用户10023919充值成功，充值的金额是:500000]
2021-01-05 20:57:05,914--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:05,914--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为空<<--接口=====]
2021-01-05 20:57:05,915--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,003--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,003--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员ID不是当前登录用户<<--接口=====]
2021-01-05 20:57:06,003--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,100--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,100--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为字符串<<--接口=====]
2021-01-05 20:57:06,100--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,195--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,196--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为小数<<--接口=====]
2021-01-05 20:57:06,197--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,299--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,299--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为空<<--接口=====]
2021-01-05 20:57:06,299--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,383--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,384--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额大于50万<<--接口=====]
2021-01-05 20:57:06,384--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,481--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,482--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为3位小数<<--接口=====]
2021-01-05 20:57:06,482--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,564--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,564--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为负数<<--接口=====]
2021-01-05 20:57:06,565--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,658--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,659--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为非数字<<--接口=====]
2021-01-05 20:57:06,659--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,749--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,749--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为0<<--接口=====]
2021-01-05 20:57:06,750--->>[test_recharge.py--->line:61--INFO-->>该用户:10023919开始充值]
2021-01-05 20:57:06,886--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:57:06,886--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023919, 'amount': 0}]
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023919, 'amount': 0}]
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023919, 'leave_amount': 510200.43, 'mobile_phone': '18427029214', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 20:57:04.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:57:06,888--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023919, 'leave_amount': 510200.43, 'mobile_phone': '18427029214', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 20:57:04.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:57:06,888--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:57:06,888--->>[base_test_case.py--->line:36--INFO-->>开始测试注册接口]
2021-01-05 20:57:06,948--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：13001768453]
2021-01-05 20:57:07,052--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '13001768453' and type =0 ]
2021-01-05 20:57:07,052--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '13001768453' and type =0 ]
2021-01-05 20:57:07,102--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:07,155--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：13520703622]
2021-01-05 20:57:07,554--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '13520703622' and type =0]
2021-01-05 20:57:07,554--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '13520703622' and type =0]
2021-01-05 20:57:07,602--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:07,655--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：15680426012]
2021-01-05 20:57:07,765--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15680426012' and type =1]
2021-01-05 20:57:07,765--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15680426012' and type =1]
2021-01-05 20:57:07,825--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:07,908--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:07,997--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,083--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,165--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,266--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,359--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,443--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,541--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,660--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,851--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:57:08,851--->>[base_test_case.py--->line:36--INFO-->>开始测试提现接口]
2021-01-05 20:57:08,903--->>[test_withdraw.py--->line:32--INFO-->>生成的手机号是:15442896171]
2021-01-05 20:57:08,903--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15442896171', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:57:08,997--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:57:08,997--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:57:08,997--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:57:08,997--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:08,855--->>[base_test_case.py--->line:36--INFO-->>开始测试加标接口]
2021-01-05 20:58:08,918--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18874669798', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:58:09,033--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:58:09,033--->>[test_add_project.py--->line:34--INFO-->>加标接口生成的手机号是:18874669798]
2021-01-05 20:58:09,034--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18874669798]
2021-01-05 20:58:09,148--->>[fixture.py--->line:59--INFO-->>用户:10023923登录成功]
2021-01-05 20:58:09,148--->>[test_add_project.py--->line:39--INFO-->>该用户是:10023923,登录成功]
2021-01-05 20:58:09,148--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标成功<<--接口]
2021-01-05 20:58:09,242--->>[test_add_project.py--->line:72--INFO-->>查询用户:10023923加标的sql是:select id from loan where member_id=10023923 and amount=2000 and title='yuejie专贷' and loan_date_type=1]
2021-01-05 20:58:09,291--->>[test_add_project.py--->line:74--INFO-->>该用户:10023923加标成功]
2021-01-05 20:58:09,291--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,292--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id为空<<--接口]
2021-01-05 20:58:09,387--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,387--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不是当前登录<<--接口]
2021-01-05 20:58:09,482--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,482--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不存在<<--接口]
2021-01-05 20:58:09,594--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,594--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--标题为空<<--接口]
2021-01-05 20:58:09,681--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,682--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为空<<--接口]
2021-01-05 20:58:09,783--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,784--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--年利率为空<<--接口]
2021-01-05 20:58:09,865--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,865--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限为空<<--接口]
2021-01-05 20:58:09,967--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:09,967--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型为空<<--接口]
2021-01-05 20:58:10,057--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,058--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数为空<<--接口]
2021-01-05 20:58:10,148--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,148--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型不是1和2<<--接口]
2021-01-05 20:58:10,245--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,246--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数大于10天<<--接口]
2021-01-05 20:58:10,352--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,352--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为负数<<--接口]
2021-01-05 20:58:10,451--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,451--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为小数<<--接口]
2021-01-05 20:58:10,546--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 20:58:10,546--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 20:58:10,602--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:15353192392]
2021-01-05 20:58:10,603--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15353192392', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:58:10,712--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:58:10,713--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15353192392]
2021-01-05 20:58:10,812--->>[fixture.py--->line:59--INFO-->>用户:10023924登录成功]
2021-01-05 20:58:10,872--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:18214186140]
2021-01-05 20:58:10,872--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18214186140', 'pwd': '12345678', 'type': 0}]
2021-01-05 20:58:10,975--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:58:10,976--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18214186140]
2021-01-05 20:58:11,072--->>[fixture.py--->line:59--INFO-->>用户:10023925登录成功]
2021-01-05 20:58:11,169--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26348]
2021-01-05 20:58:11,170--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 20:58:11,313--->>[test_audit_project.py--->line:88--INFO-->>项目26348审核通过]
2021-01-05 20:58:11,314--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:11,397--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26349]
2021-01-05 20:58:11,397--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败<<---接口]
2021-01-05 20:58:11,539--->>[test_audit_project.py--->line:93--INFO-->>项目26349审核失败]
2021-01-05 20:58:11,540--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:11,629--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26350]
2021-01-05 20:58:11,629--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id为空<<---接口]
2021-01-05 20:58:11,749--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:11,850--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26351]
2021-01-05 20:58:11,850--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id不存在<<---接口]
2021-01-05 20:58:11,938--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:12,043--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26352]
2021-01-05 20:58:12,044--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目ID为字符串<<---接口]
2021-01-05 20:58:12,132--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:12,221--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26353]
2021-01-05 20:58:12,221--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--多次审核<<---接口]
2021-01-05 20:58:12,322--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:58:12,322--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:58:12,327--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26353, 'approved_or_not': False}]
2021-01-05 20:58:12,327--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26353, 'approved_or_not': False}]
2021-01-05 20:58:12,328--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:58:12,328--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 20:58:12,328--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:12,328--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:12,328--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:12,425--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26354]
2021-01-05 20:58:12,426--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不存在<<---接口]
2021-01-05 20:58:12,505--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:12,610--->>[fixture.py--->line:119--INFO-->>该用户10023924加标借款成功:金额是:2000,该标的id是:26355]
2021-01-05 20:58:12,610--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不是true和false<<---接口]
2021-01-05 20:58:12,705--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 20:58:12,706--->>[base_test_case.py--->line:36--INFO-->>开始测试登录接口]
2021-01-05 20:58:12,821--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:58:12,925--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:58:13,010--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:58:13,103--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:58:13,207--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 20:58:13,207--->>[base_test_case.py--->line:36--INFO-->>开始测试充值接口]
2021-01-05 20:58:13,269--->>[test_recharge.py--->line:34--INFO-->>测试充值接口生成的手机号是:13051956144]
2021-01-05 20:58:13,269--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13051956144', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:58:13,371--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 20:58:13,371--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13051956144]
2021-01-05 20:58:13,478--->>[fixture.py--->line:59--INFO-->>用户:10023926登录成功]
2021-01-05 20:58:13,478--->>[test_recharge.py--->line:40--INFO-->>当前用户10023926登录成功]
2021-01-05 20:58:13,478--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--整数<<--接口=====]
2021-01-05 20:58:13,479--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023926充值之前的sql是:select leave_amount from member where id='10023926']
2021-01-05 20:58:13,524--->>[test_recharge.py--->line:56--INFO-->>该用户:10023926充值之前的余额是:0.00]
2021-01-05 20:58:13,524--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:13,666--->>[test_recharge.py--->line:78--INFO-->>该用户:10023926,充值之后的余额是:10000.00]
2021-01-05 20:58:13,666--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023926充值成功]
2021-01-05 20:58:13,667--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:58:13,667--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023926是否生成流水账单]
2021-01-05 20:58:13,667--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023926 生成流水账单的sql是:select id from financelog where income_member_id='10023926' and amount=10000 and income_member_money=10000.00]
2021-01-05 20:58:13,728--->>[test_recharge.py--->line:106--INFO-->>该用户:10023926生成流水账单校验通过]
2021-01-05 20:58:13,729--->>[test_recharge.py--->line:107--INFO-->>该用户10023926充值成功，充值的金额是:10000]
2021-01-05 20:58:13,729--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:13,729--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--一位小数<<--接口=====]
2021-01-05 20:58:13,730--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023926充值之前的sql是:select leave_amount from member where id='10023926']
2021-01-05 20:58:13,772--->>[test_recharge.py--->line:56--INFO-->>该用户:10023926充值之前的余额是:10000.00]
2021-01-05 20:58:13,773--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:13,915--->>[test_recharge.py--->line:78--INFO-->>该用户:10023926,充值之后的余额是:10100.20]
2021-01-05 20:58:13,916--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023926充值成功]
2021-01-05 20:58:13,916--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:58:13,916--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023926是否生成流水账单]
2021-01-05 20:58:13,916--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023926 生成流水账单的sql是:select id from financelog where income_member_id='10023926' and amount=100.2 and income_member_money=10100.20]
2021-01-05 20:58:13,973--->>[test_recharge.py--->line:106--INFO-->>该用户:10023926生成流水账单校验通过]
2021-01-05 20:58:13,973--->>[test_recharge.py--->line:107--INFO-->>该用户10023926充值成功，充值的金额是:100.2]
2021-01-05 20:58:13,973--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:13,974--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--2位小数<<--接口=====]
2021-01-05 20:58:13,974--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023926充值之前的sql是:select leave_amount from member where id='10023926']
2021-01-05 20:58:14,016--->>[test_recharge.py--->line:56--INFO-->>该用户:10023926充值之前的余额是:10100.20]
2021-01-05 20:58:14,016--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,149--->>[test_recharge.py--->line:78--INFO-->>该用户:10023926,充值之后的余额是:10200.43]
2021-01-05 20:58:14,149--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023926充值成功]
2021-01-05 20:58:14,149--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:58:14,149--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023926是否生成流水账单]
2021-01-05 20:58:14,149--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023926 生成流水账单的sql是:select id from financelog where income_member_id='10023926' and amount=100.23 and income_member_money=10200.43]
2021-01-05 20:58:14,204--->>[test_recharge.py--->line:106--INFO-->>该用户:10023926生成流水账单校验通过]
2021-01-05 20:58:14,205--->>[test_recharge.py--->line:107--INFO-->>该用户10023926充值成功，充值的金额是:100.23]
2021-01-05 20:58:14,205--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,205--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--50万<<--接口=====]
2021-01-05 20:58:14,205--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023926充值之前的sql是:select leave_amount from member where id='10023926']
2021-01-05 20:58:14,248--->>[test_recharge.py--->line:56--INFO-->>该用户:10023926充值之前的余额是:10200.43]
2021-01-05 20:58:14,248--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,394--->>[test_recharge.py--->line:78--INFO-->>该用户:10023926,充值之后的余额是:510200.43]
2021-01-05 20:58:14,394--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023926充值成功]
2021-01-05 20:58:14,394--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 20:58:14,394--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023926是否生成流水账单]
2021-01-05 20:58:14,395--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023926 生成流水账单的sql是:select id from financelog where income_member_id='10023926' and amount=500000 and income_member_money=510200.43]
2021-01-05 20:58:14,450--->>[test_recharge.py--->line:106--INFO-->>该用户:10023926生成流水账单校验通过]
2021-01-05 20:58:14,450--->>[test_recharge.py--->line:107--INFO-->>该用户10023926充值成功，充值的金额是:500000]
2021-01-05 20:58:14,450--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,451--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为空<<--接口=====]
2021-01-05 20:58:14,451--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,548--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,549--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员ID不是当前登录用户<<--接口=====]
2021-01-05 20:58:14,549--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,645--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,645--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为字符串<<--接口=====]
2021-01-05 20:58:14,645--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,740--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,740--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为小数<<--接口=====]
2021-01-05 20:58:14,741--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,839--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,839--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为空<<--接口=====]
2021-01-05 20:58:14,840--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:14,926--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:14,926--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额大于50万<<--接口=====]
2021-01-05 20:58:14,926--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:15,015--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:15,015--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为3位小数<<--接口=====]
2021-01-05 20:58:15,016--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:15,118--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:15,118--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为负数<<--接口=====]
2021-01-05 20:58:15,118--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:15,216--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:15,217--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为非数字<<--接口=====]
2021-01-05 20:58:15,217--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:15,304--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:15,304--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为0<<--接口=====]
2021-01-05 20:58:15,305--->>[test_recharge.py--->line:61--INFO-->>该用户:10023926开始充值]
2021-01-05 20:58:15,390--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:58:15,390--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023926, 'amount': 0}]
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023926, 'amount': 0}]
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023926, 'leave_amount': 510200.43, 'mobile_phone': '13051956144', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 20:58:13.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:15,392--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023926, 'leave_amount': 510200.43, 'mobile_phone': '13051956144', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 20:58:13.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:15,392--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 20:58:15,393--->>[base_test_case.py--->line:36--INFO-->>开始测试注册接口]
2021-01-05 20:58:15,447--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：18110861972]
2021-01-05 20:58:15,570--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '18110861972' and type =0 ]
2021-01-05 20:58:15,570--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '18110861972' and type =0 ]
2021-01-05 20:58:15,621--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:15,679--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：15806373126]
2021-01-05 20:58:15,782--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15806373126' and type =0]
2021-01-05 20:58:15,782--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15806373126' and type =0]
2021-01-05 20:58:15,841--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:15,899--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：18641329201]
2021-01-05 20:58:16,002--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '18641329201' and type =1]
2021-01-05 20:58:16,002--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '18641329201' and type =1]
2021-01-05 20:58:16,056--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,144--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,247--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,345--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,432--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,538--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,624--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,708--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,795--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,884--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,980--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 20:58:16,980--->>[base_test_case.py--->line:36--INFO-->>开始测试提现接口]
2021-01-05 20:58:17,038--->>[test_withdraw.py--->line:32--INFO-->>生成的手机号是:15466134438]
2021-01-05 20:58:17,038--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15466134438', 'pwd': '12345678', 'type': 1}]
2021-01-05 20:58:17,123--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:58:17,123--->>[fixture.py--->line:37--ERROR-->>注册用户失败]
2021-01-05 20:58:17,124--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 20:58:17,124--->>[fixture.py--->line:38--ERROR-->>错误信息是:{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 21:00:11,703--->>[base_test_case.py--->line:36--INFO-->>开始测试加标接口]
2021-01-05 21:00:11,761--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18911440349', 'pwd': '12345678', 'type': 1}]
2021-01-05 21:00:11,879--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 21:00:11,879--->>[test_add_project.py--->line:34--INFO-->>加标接口生成的手机号是:18911440349]
2021-01-05 21:00:11,880--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18911440349]
2021-01-05 21:00:11,995--->>[fixture.py--->line:59--INFO-->>用户:10023930登录成功]
2021-01-05 21:00:11,995--->>[test_add_project.py--->line:39--INFO-->>该用户是:10023930,登录成功]
2021-01-05 21:00:11,995--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标成功<<--接口]
2021-01-05 21:00:12,102--->>[test_add_project.py--->line:72--INFO-->>查询用户:10023930加标的sql是:select id from loan where member_id=10023930 and amount=2000 and title='yuejie专贷' and loan_date_type=1]
2021-01-05 21:00:12,154--->>[test_add_project.py--->line:74--INFO-->>该用户:10023930加标成功]
2021-01-05 21:00:12,154--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,155--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id为空<<--接口]
2021-01-05 21:00:12,250--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,250--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不是当前登录<<--接口]
2021-01-05 21:00:12,349--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,349--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--用户id不存在<<--接口]
2021-01-05 21:00:12,431--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,431--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--标题为空<<--接口]
2021-01-05 21:00:12,524--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,524--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为空<<--接口]
2021-01-05 21:00:12,611--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,611--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--年利率为空<<--接口]
2021-01-05 21:00:12,703--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,703--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限为空<<--接口]
2021-01-05 21:00:12,795--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,795--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型为空<<--接口]
2021-01-05 21:00:12,880--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,880--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数为空<<--接口]
2021-01-05 21:00:12,965--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:12,966--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款期限类型不是1和2<<--接口]
2021-01-05 21:00:13,067--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:13,067--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--竞标天数大于10天<<--接口]
2021-01-05 21:00:13,150--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:13,150--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为负数<<--接口]
2021-01-05 21:00:13,253--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:13,253--->>[test_add_project.py--->line:43--INFO-->>开始测试-->>加标失败--借款金额为小数<<--接口]
2021-01-05 21:00:13,335--->>[base_test_case.py--->line:40--INFO-->>加标接口功能结束]
2021-01-05 21:00:13,336--->>[base_test_case.py--->line:36--INFO-->>开始测试审核项目接口]
2021-01-05 21:00:13,392--->>[test_audit_project.py--->line:34--INFO-->>审核项目生成的普通用户手机号是:18374051671]
2021-01-05 21:00:13,392--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '18374051671', 'pwd': '12345678', 'type': 1}]
2021-01-05 21:00:13,492--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 21:00:13,492--->>[fixture.py--->line:56--INFO-->>该用户开始登录:18374051671]
2021-01-05 21:00:13,586--->>[fixture.py--->line:59--INFO-->>用户:10023931登录成功]
2021-01-05 21:00:13,645--->>[test_audit_project.py--->line:43--INFO-->>生成管理员用户的手机号是:13597495777]
2021-01-05 21:00:13,646--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13597495777', 'pwd': '12345678', 'type': 0}]
2021-01-05 21:00:13,753--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 21:00:13,753--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13597495777]
2021-01-05 21:00:13,868--->>[fixture.py--->line:59--INFO-->>用户:10023932登录成功]
2021-01-05 21:00:13,960--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26357]
2021-01-05 21:00:13,960--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核成功<<---接口]
2021-01-05 21:00:14,102--->>[test_audit_project.py--->line:88--INFO-->>项目26357审核通过]
2021-01-05 21:00:14,103--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:14,194--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26358]
2021-01-05 21:00:14,195--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败<<---接口]
2021-01-05 21:00:14,326--->>[test_audit_project.py--->line:93--INFO-->>项目26358审核失败]
2021-01-05 21:00:14,326--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:14,419--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26359]
2021-01-05 21:00:14,420--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id为空<<---接口]
2021-01-05 21:00:14,504--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:14,603--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26360]
2021-01-05 21:00:14,603--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目id不存在<<---接口]
2021-01-05 21:00:14,713--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:14,823--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26361]
2021-01-05 21:00:14,823--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--项目ID为字符串<<---接口]
2021-01-05 21:00:14,915--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:15,017--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26362]
2021-01-05 21:00:15,018--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--多次审核<<---接口]
2021-01-05 21:00:15,113--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 21:00:15,113--->>[test_audit_project.py--->line:76--ERROR-->>审核失败--多次审核:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_audit_project.py", line 73, in test_audit_project
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26362, 'approved_or_not': False}]
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:77--WARNING-->>请求数据是:{'loan_id': 26362, 'approved_or_not': False}]
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:78--WARNING-->>期望结果是:{'code': 2, 'msg': '项目不在审核中状态'}]
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 21:00:15,118--->>[test_audit_project.py--->line:79--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 21:00:15,118--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:15,224--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26363]
2021-01-05 21:00:15,224--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不存在<<---接口]
2021-01-05 21:00:15,325--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:15,422--->>[fixture.py--->line:119--INFO-->>该用户10023931加标借款成功:金额是:2000,该标的id是:26364]
2021-01-05 21:00:15,423--->>[test_audit_project.py--->line:61--INFO-->>开始测试--->>审核失败--审核状态不是true和false<<---接口]
2021-01-05 21:00:15,504--->>[base_test_case.py--->line:40--INFO-->>审核项目接口功能结束]
2021-01-05 21:00:15,504--->>[base_test_case.py--->line:36--INFO-->>开始测试登录接口]
2021-01-05 21:00:15,613--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 21:00:15,710--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 21:00:15,805--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 21:00:15,921--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 21:00:16,057--->>[base_test_case.py--->line:40--INFO-->>登录接口功能结束]
2021-01-05 21:00:16,058--->>[base_test_case.py--->line:36--INFO-->>开始测试充值接口]
2021-01-05 21:00:16,118--->>[test_recharge.py--->line:34--INFO-->>测试充值接口生成的手机号是:13026057332]
2021-01-05 21:00:16,118--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '13026057332', 'pwd': '12345678', 'type': 1}]
2021-01-05 21:00:16,231--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 21:00:16,232--->>[fixture.py--->line:56--INFO-->>该用户开始登录:13026057332]
2021-01-05 21:00:16,344--->>[fixture.py--->line:59--INFO-->>用户:10023933登录成功]
2021-01-05 21:00:16,344--->>[test_recharge.py--->line:40--INFO-->>当前用户10023933登录成功]
2021-01-05 21:00:16,345--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--整数<<--接口=====]
2021-01-05 21:00:16,345--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023933充值之前的sql是:select leave_amount from member where id='10023933']
2021-01-05 21:00:16,392--->>[test_recharge.py--->line:56--INFO-->>该用户:10023933充值之前的余额是:0.00]
2021-01-05 21:00:16,392--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:16,568--->>[test_recharge.py--->line:78--INFO-->>该用户:10023933,充值之后的余额是:10000.00]
2021-01-05 21:00:16,568--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023933充值成功]
2021-01-05 21:00:16,569--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 21:00:16,569--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023933是否生成流水账单]
2021-01-05 21:00:16,569--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023933 生成流水账单的sql是:select id from financelog where income_member_id='10023933' and amount=10000 and income_member_money=10000.00]
2021-01-05 21:00:16,637--->>[test_recharge.py--->line:106--INFO-->>该用户:10023933生成流水账单校验通过]
2021-01-05 21:00:16,638--->>[test_recharge.py--->line:107--INFO-->>该用户10023933充值成功，充值的金额是:10000]
2021-01-05 21:00:16,638--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:16,638--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--一位小数<<--接口=====]
2021-01-05 21:00:16,638--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023933充值之前的sql是:select leave_amount from member where id='10023933']
2021-01-05 21:00:16,685--->>[test_recharge.py--->line:56--INFO-->>该用户:10023933充值之前的余额是:10000.00]
2021-01-05 21:00:16,685--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:16,823--->>[test_recharge.py--->line:78--INFO-->>该用户:10023933,充值之后的余额是:10100.20]
2021-01-05 21:00:16,824--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023933充值成功]
2021-01-05 21:00:16,824--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 21:00:16,824--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023933是否生成流水账单]
2021-01-05 21:00:16,824--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023933 生成流水账单的sql是:select id from financelog where income_member_id='10023933' and amount=100.2 and income_member_money=10100.20]
2021-01-05 21:00:16,898--->>[test_recharge.py--->line:106--INFO-->>该用户:10023933生成流水账单校验通过]
2021-01-05 21:00:16,898--->>[test_recharge.py--->line:107--INFO-->>该用户10023933充值成功，充值的金额是:100.2]
2021-01-05 21:00:16,898--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:16,899--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--2位小数<<--接口=====]
2021-01-05 21:00:16,899--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023933充值之前的sql是:select leave_amount from member where id='10023933']
2021-01-05 21:00:16,942--->>[test_recharge.py--->line:56--INFO-->>该用户:10023933充值之前的余额是:10100.20]
2021-01-05 21:00:16,943--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,083--->>[test_recharge.py--->line:78--INFO-->>该用户:10023933,充值之后的余额是:10200.43]
2021-01-05 21:00:17,083--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023933充值成功]
2021-01-05 21:00:17,083--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 21:00:17,083--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023933是否生成流水账单]
2021-01-05 21:00:17,083--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023933 生成流水账单的sql是:select id from financelog where income_member_id='10023933' and amount=100.23 and income_member_money=10200.43]
2021-01-05 21:00:17,142--->>[test_recharge.py--->line:106--INFO-->>该用户:10023933生成流水账单校验通过]
2021-01-05 21:00:17,142--->>[test_recharge.py--->line:107--INFO-->>该用户10023933充值成功，充值的金额是:100.23]
2021-01-05 21:00:17,142--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,143--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值成功--50万<<--接口=====]
2021-01-05 21:00:17,143--->>[test_recharge.py--->line:53--INFO-->>查询该用户:10023933充值之前的sql是:select leave_amount from member where id='10023933']
2021-01-05 21:00:17,186--->>[test_recharge.py--->line:56--INFO-->>该用户:10023933充值之前的余额是:10200.43]
2021-01-05 21:00:17,186--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,340--->>[test_recharge.py--->line:78--INFO-->>该用户:10023933,充值之后的余额是:510200.43]
2021-01-05 21:00:17,341--->>[test_recharge.py--->line:84--INFO-->>数据库校验成功,该用户10023933充值成功]
2021-01-05 21:00:17,341--->>[test_recharge.py--->line:93--INFO-->>数据库余额和当前接口返回是一致]
2021-01-05 21:00:17,341--->>[test_recharge.py--->line:100--INFO-->>开始校验该用户:10023933是否生成流水账单]
2021-01-05 21:00:17,341--->>[test_recharge.py--->line:104--INFO-->>校验该用户:10023933 生成流水账单的sql是:select id from financelog where income_member_id='10023933' and amount=500000 and income_member_money=510200.43]
2021-01-05 21:00:17,398--->>[test_recharge.py--->line:106--INFO-->>该用户:10023933生成流水账单校验通过]
2021-01-05 21:00:17,398--->>[test_recharge.py--->line:107--INFO-->>该用户10023933充值成功，充值的金额是:500000]
2021-01-05 21:00:17,399--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,399--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为空<<--接口=====]
2021-01-05 21:00:17,399--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,485--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,486--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员ID不是当前登录用户<<--接口=====]
2021-01-05 21:00:17,486--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,580--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,581--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为字符串<<--接口=====]
2021-01-05 21:00:17,581--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,673--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,674--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--会员id为小数<<--接口=====]
2021-01-05 21:00:17,674--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,775--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,776--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为空<<--接口=====]
2021-01-05 21:00:17,776--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,860--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,861--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额大于50万<<--接口=====]
2021-01-05 21:00:17,861--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:17,952--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:17,953--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为3位小数<<--接口=====]
2021-01-05 21:00:17,953--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:18,041--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:18,042--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为负数<<--接口=====]
2021-01-05 21:00:18,042--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:18,124--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:18,125--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为非数字<<--接口=====]
2021-01-05 21:00:18,125--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:18,214--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:18,214--->>[test_recharge.py--->line:45--INFO-->>===开始测试->>充值失败--金额为0<<--接口=====]
2021-01-05 21:00:18,214--->>[test_recharge.py--->line:61--INFO-->>该用户:10023933开始充值]
2021-01-05 21:00:18,312--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 21:00:18,312--->>[test_recharge.py--->line:70--ERROR-->>充值失败--金额为0:测试失败]
Traceback (most recent call last):
  File "/Users/yantianpeng/PycharmProjects/beidouxing888/beidouxingauto_project/testcases/test_recharge.py", line 66, in test_recharge
    self.assertEqual(rel_data['code'],expect_data['code']);
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023933, 'amount': 0}]
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:71--WARNING-->>请求数据是:{'member_id': 10023933, 'amount': 0}]
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:72--WARNING-->>期望数据是:{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000'}]
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023933, 'leave_amount': 510200.43, 'mobile_phone': '13026057332', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 21:00:16.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 21:00:18,315--->>[test_recharge.py--->line:73--WARNING-->>实际结果是:{'code': 0, 'msg': 'OK', 'data': {'id': 10023933, 'leave_amount': 510200.43, 'mobile_phone': '13026057332', 'reg_name': '小柠檬', 'reg_time': '2021-01-05 21:00:16.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}]
2021-01-05 21:00:18,316--->>[base_test_case.py--->line:40--INFO-->>充值接口功能结束]
2021-01-05 21:00:18,316--->>[base_test_case.py--->line:36--INFO-->>开始测试注册接口]
2021-01-05 21:00:18,374--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：13182654505]
2021-01-05 21:00:18,484--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '13182654505' and type =0 ]
2021-01-05 21:00:18,484--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id from member where mobile_phone = '13182654505' and type =0 ]
2021-01-05 21:00:18,536--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:18,595--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：15366096431]
2021-01-05 21:00:18,711--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15366096431' and type =0]
2021-01-05 21:00:18,711--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15366096431' and type =0]
2021-01-05 21:00:18,766--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:18,823--->>[test_register.py--->line:32--INFO-->>生成的手机号码是：15905452177]
2021-01-05 21:00:18,926--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15905452177' and type =1]
2021-01-05 21:00:18,926--->>[test_register.py--->line:66--WARNING-->>数据库校验执行的sql:select id  from member where mobile_phone = '15905452177' and type =1]
2021-01-05 21:00:18,994--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,079--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,163--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,258--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,344--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,443--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,528--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,619--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,722--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,810--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,893--->>[base_test_case.py--->line:40--INFO-->>注册接口功能结束]
2021-01-05 21:00:19,894--->>[base_test_case.py--->line:36--INFO-->>开始测试提现接口]
2021-01-05 21:00:19,950--->>[test_withdraw.py--->line:32--INFO-->>生成的手机号是:15776480379]
2021-01-05 21:00:19,950--->>[fixture.py--->line:32--INFO-->>开始注册用户:{'mobile_phone': '15776480379', 'pwd': '12345678', 'type': 1}]
2021-01-05 21:00:20,048--->>[fixture.py--->line:35--INFO-->>注册用户成功]
2021-01-05 21:00:20,049--->>[fixture.py--->line:56--INFO-->>该用户开始登录:15776480379]
2021-01-05 21:00:20,151--->>[fixture.py--->line:59--INFO-->>用户:10023937登录成功]
2021-01-05 21:00:20,151--->>[fixture.py--->line:82--INFO-->>用户:10023937,充值:500000元]
2021-01-05 21:00:20,261--->>[fixture.py--->line:85--INFO-->>用户:10023937充值成功]
2021-01-05 21:00:20,261--->>[fixture.py--->line:82--INFO-->>用户:10023937,充值:100000元]
2021-01-05 21:00:20,351--->>[fixture.py--->line:85--INFO-->>用户:10023937充值成功]
2021-01-05 21:00:20,351--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现成功--整数===]
2021-01-05 21:00:20,395--->>[test_withdraw.py--->line:55--INFO-->>查询提前之前的余额的sql是:select leave_amount from member where id=10023937]
2021-01-05 21:00:20,395--->>[test_withdraw.py--->line:56--INFO-->>用户10023937提现之前的余额是:600000.00]
2021-01-05 21:00:20,487--->>[test_withdraw.py--->line:66--INFO-->>===测试提现成功--整数结束====]
2021-01-05 21:00:20,532--->>[test_withdraw.py--->line:76--INFO-->>用户10023937提现之前的余额是:{'leave_amount': Decimal('599000.00')}]
2021-01-05 21:00:20,532--->>[test_withdraw.py--->line:86--INFO-->>===校验是否生成流水账单=======]
2021-01-05 21:00:20,532--->>[test_withdraw.py--->line:89--INFO-->>生成流水账单的sql是:select id from financeLog where pay_member_id=10023937 and amount=1000 and pay_member_money =599000.00 ]
2021-01-05 21:00:20,588--->>[test_withdraw.py--->line:91--INFO-->>=====流水账单生成成功=======]
2021-01-05 21:00:20,589--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:20,589--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现成功--1位小数===]
2021-01-05 21:00:20,632--->>[test_withdraw.py--->line:55--INFO-->>查询提前之前的余额的sql是:select leave_amount from member where id=10023937]
2021-01-05 21:00:20,632--->>[test_withdraw.py--->line:56--INFO-->>用户10023937提现之前的余额是:599000.00]
2021-01-05 21:00:20,729--->>[test_withdraw.py--->line:66--INFO-->>===测试提现成功--1位小数结束====]
2021-01-05 21:00:20,775--->>[test_withdraw.py--->line:76--INFO-->>用户10023937提现之前的余额是:{'leave_amount': Decimal('590111.20')}]
2021-01-05 21:00:20,775--->>[test_withdraw.py--->line:86--INFO-->>===校验是否生成流水账单=======]
2021-01-05 21:00:20,775--->>[test_withdraw.py--->line:89--INFO-->>生成流水账单的sql是:select id from financeLog where pay_member_id=10023937 and amount=8888.8 and pay_member_money =590111.20 ]
2021-01-05 21:00:20,831--->>[test_withdraw.py--->line:91--INFO-->>=====流水账单生成成功=======]
2021-01-05 21:00:20,831--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:20,832--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现成功--2位小数===]
2021-01-05 21:00:20,877--->>[test_withdraw.py--->line:55--INFO-->>查询提前之前的余额的sql是:select leave_amount from member where id=10023937]
2021-01-05 21:00:20,877--->>[test_withdraw.py--->line:56--INFO-->>用户10023937提现之前的余额是:590111.20]
2021-01-05 21:00:20,964--->>[test_withdraw.py--->line:66--INFO-->>===测试提现成功--2位小数结束====]
2021-01-05 21:00:21,007--->>[test_withdraw.py--->line:76--INFO-->>用户10023937提现之前的余额是:{'leave_amount': Decimal('581222.32')}]
2021-01-05 21:00:21,007--->>[test_withdraw.py--->line:86--INFO-->>===校验是否生成流水账单=======]
2021-01-05 21:00:21,007--->>[test_withdraw.py--->line:89--INFO-->>生成流水账单的sql是:select id from financeLog where pay_member_id=10023937 and amount=8888.88 and pay_member_money =581222.32 ]
2021-01-05 21:00:21,063--->>[test_withdraw.py--->line:91--INFO-->>=====流水账单生成成功=======]
2021-01-05 21:00:21,064--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,064--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现成功--提现金额为0===]
2021-01-05 21:00:21,108--->>[test_withdraw.py--->line:55--INFO-->>查询提前之前的余额的sql是:select leave_amount from member where id=10023937]
2021-01-05 21:00:21,108--->>[test_withdraw.py--->line:56--INFO-->>用户10023937提现之前的余额是:581222.32]
2021-01-05 21:00:21,204--->>[test_withdraw.py--->line:66--INFO-->>===测试提现成功--提现金额为0结束====]
2021-01-05 21:00:21,249--->>[test_withdraw.py--->line:76--INFO-->>用户10023937提现之前的余额是:{'leave_amount': Decimal('581222.32')}]
2021-01-05 21:00:21,249--->>[test_withdraw.py--->line:86--INFO-->>===校验是否生成流水账单=======]
2021-01-05 21:00:21,249--->>[test_withdraw.py--->line:89--INFO-->>生成流水账单的sql是:select id from financeLog where pay_member_id=10023937 and amount=0 and pay_member_money =581222.32 ]
2021-01-05 21:00:21,303--->>[test_withdraw.py--->line:91--INFO-->>=====流水账单生成成功=======]
2021-01-05 21:00:21,304--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,304--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现成功--50万提现===]
2021-01-05 21:00:21,348--->>[test_withdraw.py--->line:55--INFO-->>查询提前之前的余额的sql是:select leave_amount from member where id=10023937]
2021-01-05 21:00:21,348--->>[test_withdraw.py--->line:56--INFO-->>用户10023937提现之前的余额是:581222.32]
2021-01-05 21:00:21,455--->>[test_withdraw.py--->line:66--INFO-->>===测试提现成功--50万提现结束====]
2021-01-05 21:00:21,499--->>[test_withdraw.py--->line:76--INFO-->>用户10023937提现之前的余额是:{'leave_amount': Decimal('81222.32')}]
2021-01-05 21:00:21,499--->>[test_withdraw.py--->line:86--INFO-->>===校验是否生成流水账单=======]
2021-01-05 21:00:21,499--->>[test_withdraw.py--->line:89--INFO-->>生成流水账单的sql是:select id from financeLog where pay_member_id=10023937 and amount=500000 and pay_member_money =81222.32 ]
2021-01-05 21:00:21,553--->>[test_withdraw.py--->line:91--INFO-->>=====流水账单生成成功=======]
2021-01-05 21:00:21,554--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,554--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--提现金额大于余额===]
2021-01-05 21:00:21,651--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--提现金额大于余额结束====]
2021-01-05 21:00:21,651--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,651--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--提现金额大于50万===]
2021-01-05 21:00:21,743--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--提现金额大于50万结束====]
2021-01-05 21:00:21,744--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,744--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--体现金额3位小数===]
2021-01-05 21:00:21,842--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--体现金额3位小数结束====]
2021-01-05 21:00:21,842--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,842--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--提现金额为负数===]
2021-01-05 21:00:21,928--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--提现金额为负数结束====]
2021-01-05 21:00:21,928--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:21,928--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--提现金额包含特殊符号===]
2021-01-05 21:00:22,023--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--提现金额包含特殊符号结束====]
2021-01-05 21:00:22,023--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:22,023--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--提现金额为空===]
2021-01-05 21:00:22,117--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--提现金额为空结束====]
2021-01-05 21:00:22,118--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:22,119--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--用户id为空===]
2021-01-05 21:00:22,221--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--用户id为空结束====]
2021-01-05 21:00:22,221--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:22,221--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--用户id不是当前登录用户===]
2021-01-05 21:00:22,323--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--用户id不是当前登录用户结束====]
2021-01-05 21:00:22,324--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
2021-01-05 21:00:22,324--->>[test_withdraw.py--->line:44--INFO-->>===开始测试提现失败--用户id为数值===]
2021-01-05 21:00:22,418--->>[test_withdraw.py--->line:66--INFO-->>===测试提现失败--用户id为数值结束====]
2021-01-05 21:00:22,418--->>[base_test_case.py--->line:40--INFO-->>提现接口功能结束]
