{"name": "test_01[4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <test_case_04.Test_abc_03 object at 0x109a7edc0>, before = 4\n\n    def test_01(self,before):\n        print(\"----->>>>我是测试方法<<<<----\");\n>       assert 3 == before;\nE       assert 3 == 4\n\ntest_case_04.py:24: AssertionError"}, "parameters": [{"name": "before", "value": "4"}], "start": 1610631193523, "stop": 1610631193523, "uuid": "57a988bd-0644-41ba-924a-86aaf42d65cb", "historyId": "10ac3fd820254cc58b9859f53e8cb28c", "testCaseId": "f7eb19b8d4e9053f77f9cc806fb477e7", "fullName": "test_case_04.Test_abc_03#test_01", "labels": [{"name": "suite", "value": "test_case_04"}, {"name": "subSuite", "value": "Test_abc_03"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28222-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_04"}]}